[project]
name = "img-srch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.5"
dependencies = [
    "fastapi>=0.115.6",
    "uvicorn>=0.34.0",
    "watchdog>=6.0.0",
]
